### ISSUE TITLE
do we need both pylint and mypy?

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-covid-19#47]
they're redundant right - possibly could get rid of one

**Comment by callahantiff** [comment]
@justaddcoffee - great question! I did some research a while back and it seems that they are different, but in subtle ways. `Mypy`, as I think we have all experienced this week :D, is more strict than`pylint`. I use both in my personal projects, because I catch a lot of weird errors when using both. That said, I think using 1 is fine and the community consensus seems to be `pylint`.

If you agree, I'm happy to remove it from our `Travis.yml` file.

**Comment by justaddcoffee** [comment]
> I use both in my personal projects, because I catch a lot of weird errors when using both. 

In that case, we can leave both - for some reason I thought we were mistakenly running both
